 Running on myPE: 2, nei_n = -1, nei_s = 0, nei_e = 3, nei_w = -1
myPE: 2, nei_sw = -1, nei_se = 1, nei_nw = -1, nei_ne = -1
myPE: 2 Time = 0.1
myPE: 2 Time = 0.2
myPE: 2 Time = 0.3
myPE: 2 Time = 0.4
myPE: 2 Time = 0.5
myPE: 2 Time = 0.6
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2 Time = 0.7
myPE: 2 Time = 0.8
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2 Time = 0.9
myPE: 2 Time = 1
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2 Time = 1.1
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2 Time = 1.2
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2myPE: 1, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2 Time = 1.4
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2 Time = 1.5
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2 Time = 1.6
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2 Time = 1.7
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2 Time = 1.8
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:10, iPEnew:1, jPEnew:1 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2 Time = 1.9
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:1, iPEnew:0, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
myPE: 2, ptcl_send_PE:2, iPEnew:1, jPEnew:0 
